### ISSUE TITLE
No popcount compile?

### ISSUE THREAD

**Issue by rwbc** [cetincan0/Defenchess#1]
Will there be a compile for older 64 bit hardware too?

**Comment by cetincan0** [comment]
The default compile should be running a builtin popcount. I could also add a binary built without the popcnt flag if this one isn't running properly.

**Comment by cetincan0** [comment]
Please let me know if the recent release works, thanks!

**Comment by rwbc** [comment]
> 
> 
> Please let me know if the recent release works, thanks!

Tested and it works here on my Core2 Quad from 2009.

**Comment by cetincan0** [comment]
Great! Closing the issue.
