### ISSUE TITLE
Final 2.3?

### ISSUE THREAD

**Issue by CMCanavessi** [cetincan0/Defenchess#10]
Is development of Defenchess still ongoing? Are there plans to produce a final (non-dev) 2.3? I ask because I would like to use it in my FRC tournament, and 2.2 doesn't support FRC.
I know I can get dev compiles somewhere else, but it's not the same as an official release.

**Comment by cetincan0** [comment]
Defenchess is not under development anymore. You can compile the master branch for the dev version but there won’t be any new official releases.
