### ISSUE TITLE
Is this release crippled?

### ISSUE THREAD

**Issue by mobmat** [cetincan0/Defenchess#3]
running version 2.2 popcount
16GB hash, 4 threads
using the engine to solve some "mate in" puzzles.
the engine will search for awhile and then just "hang" and won't search further.
I thought the issues might be a corrupt Syzygy file, so I disabled end game tables but the same issue persists.  here is an example.
k1N4n/P7/P7/P7/P7/P7/1PK5/8 w - - 0 1 
a mate in 10 puzzle. the engine searches for 9 seconds to ply 38 showing a mate in 11. then it just stops.
this happens on many other positions as well.
is this release crippled in some way or is there an issue when solving mate problems.

**Comment by cetincan0** [comment]
The reason it's stuck is probably the lack of mate distance pruning although even when I added it to test it out, it was still unable to find the mate in 10, showing mate in 11 at depth 128. Thanks for bringing this to my attention!

**Comment by iandoug** [comment]
A four-way round-robin using a non-standard start position. The results surprised me so I came to see what Defenchess is about ... I think TCEC S17 will be "interesting".

Defenchess_2.2       : 4
Ethereal 20191110 : 3.5
andscacs                 : 2.5
Fire_7.1_x64            : 2

Win / Draw / Lose:
Defenchess_2.2   :                 3 [2/1]   2 [0/2]   1 [1/0]
