### ISSUE TITLE
Defenchess Playing Chess Variants, Musketeer Chess

### ISSUE THREAD

**Issue by musketeerchess** [cetincan0/Defenchess#5]
Hi
It'll be nice to see your engine compete in the future Musketeer Chess tournaments that i'm organising.

Some interesting issues and repositories can be found here:

http://talkchess.com/forum3/viewtopic.php?f=7&t=72572&start=10#p822789

https://github.com/ianfab/Musketeer-Stockfish/issues/3

Best regards

Dr HADDAD
www.musketeerchess.net

**Comment by cetincan0** [comment]
Hello,

Thanks for asking but I am not currently interested in implementing more chess variants other than FRC.

**Comment by musketeerchess** [comment]
Hi
Thanks for your answer.

Whenever you find time and interest please join.

The discussions on talkchess and GitHub/musketeer stockfish are very
interesting and i invite you to take a look at them.

Best regards
Zied

Le jeu. 16 janv. 2020 à 00:59, Can Cetin <notifications@github.com> a
écrit :

**Comment by servusdei2018** [comment]
> Hi Thanks for your answer. Whenever you find time and interest please join. The discussions on talkchess and GitHub/musketeer stockfish are very interesting and i invite you to take a look at them. Best regards Zied Le jeu. 16 janv. 2020 à 00:59, Can Cetin <notifications@github.com> a écrit :
> […](#)
> Hello, Thanks for asking but I am not currently interested in implementing more chess variants. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub <#5?email_source=notifications&email_token=AIIE4HNE5XNV5TES7UFLEODQ56PPRA5CNFSM4KC5DADKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJCH4JA#issuecomment-574914084>, or unsubscribe <BAD LINK -- REMOVE THIS>.

@musketeerchess , your post contains a link which, if clicked, would unsubscribe you from GitHub notifications. It may even pose a more severe security breach. I recommend that you edit out the link at the very bottom, in the quoted part.
