### ISSUE TITLE
Defenchess Played at CCCC and revealed some kind of hash bug?

### ISSUE THREAD

**Issue by TesseractA** [cetincan0/Defenchess#7]
A 7-man win was reached with a king+2 connected passed pawns+a knight vs. a king+bishop+passed edge pawn. Defenchess could not execute a win and somehow decided keeping the king in a corner was the solution, having unusually high evaluations while not realizing when its opportunity to win had passed. For the Stockfish kibitzer engine, it was the difference between night and day.

I think the repeated moves may either be due to a hash bug or incorrect tb draw avoidance.

https://www.chess.com/computer-chess-championship#event=ccc13-pool-c-bullet-test-ii&game=33
[Event "CCC13: Pool C (Bullet Test II) (1|1)"]
[Site "?"]
[Date "2020.03.06"]
[Round "1"]
[White "Defenchess"]
[Black "Rofchade"]
[Result "1/2-1/2"]
[ECO "D30"]
[GameDuration "00:08:01"]
[GameEndTime "2020-03-06T19:37:10.587 PST"]
[GameStartTime "2020-03-06T19:29:09.162 PST"]
[Opening "Queen's gambit declined"]
[PlyCount "233"]
[TimeControl "60+1"]

1. d4 d5 2. c4 e6 3. Nf3 Nf6 4. Nc3 dxc4 5. e4 Bb4 6. Bg5 c5 7. Bxc4 cxd4 8. Nxd4 Bxc3+ 9. bxc3 Qa5 10. Bxf6 Qxc3+ 11. Kf1 Qxc4+ 12. Kg1 Bd7 13. Rc1 Qb4 14. Bxg7 Rg8 15. Bf6 Rg6 16. a3 Qd6 17. e5 Qd5 18. f3 Nc6 19. Nb3 Qxd1+ 20. Rxd1 Ne7 21. Nc5 Bc6 22. Kf2 Ng8 23. Bh4 Ne7 24. h3 Rc8 25. Rc1 f5 26. Rhd1 b6 27. Nb3 Nd5 28. Nd4 Kd7 29. g4 fxg4 30. hxg4 Bb7 31. Rxc8 Bxc8 32. Bg3 Rg7 33. Rh1 Ke8 34. Rh6 Nc7 35. Bh4 a5 36. a4 Kf8 37. Bd8 Kg8 38. Kg3 Rd7 39. Nc6 Bb7 40. Bxc7 Rxc7 41. Nd4 Bc8 42. Nb5 Re7 43. Rh2 Bd7 44. Rb2 Bc6 45. f4 h6 46. Nd4 Bxa4 47. Rxb6 Bd7 48. Nb3 a4 49. Nc5 Be8 50. Ne4 Kg7 51. Ra6 Bg6 52. Nc5 Kf7 53. Kh4 Bc2 54. Kh5 Bd1 55. Nxa4 Rc7 56. Nb6 Kg7 57. Ra8 Rb7 58. Nc8 Rf7 59. Ra7 Rxa7 60. Nxa7 Ba4 61. Nc8 Be8+ 62. Kh4 Kg6 63. Nd6 Bd7 64. Ne4 Bb5 65. Nf2 Ba4 66. Nd3 Bb3 67. f5+ exf5 68. Nf4+ Kf7 69. gxf5 Bc2 70. f6 Bd1 71. Kg3 Bb3 72. Kf3 Bc2 73. Ke3 Bf5 74. Kd4 Bg4 75. Ke4 Bd1 76. Ke3 Ba4 77. Kd4 Bd1 78. Ke4 Bb3 79. Kd4 Bd1 80. Ke3 Bc2 81. Kf3 Bf5 82. Ke3 Bc2 83. Kd2 Bf5 84. Kc3 Bg4 85. Kd2 Bf5 86. Ke2 Bh7 87. Kf2 Bb1 88. Kf3 Bf5 89. Ke2 Bb1 90. Kf1 Be4 91. Kf2 Bh7 92. Kg1 Bc2 93. Kg2 Bb1 94. Kh2 Bc2 95. Kh1 Be4+ 96. Kh2 Bc2 97. Kg1 Bd1 98. Kf1 Bf3 99. Kg1 Be4 100. Kf2 Bb1 101. Ke1 Be4 102. Ke2 Bh7 103. Kf1 Bf5 104. Kg2 Be4+ 105. Kf1 Bc2 106. Kg2 Bb1 107. Kh3 Bc2 108. Kh4 Bd1 109. Kg3 Bc2 110. Kh3 Bb3 111. Kg2 Bd1 112. Kf1 Bb3 113. Kf2 Bd1 114. Kg2 Bc2 115. Kh3 Bb3 116. Kg4 Bd1+ 117. Kg3
1/2-1/2

**Comment by cetincan0** [comment]
Thanks for reporting this, I tried reproducing this with the current dev version but wasn't able to, I'm hoping that it was due to a combination of problems with the hash table and high thread count coupled with low time control.

**Comment by TesseractA** [comment]
Maybe it had to do with tablebases? Not sure exactly what TB CCCC uses, but I think they use partial 7-man tablebases.

https://cccfiles.chess.com/archive/7man-tablebases.html
